//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite
    {
        public int favorite_id { get; set; }
        public int user_id { get; set; }
        public int comic_id { get; set; }
        public Nullable<System.DateTime> favorite_date { get; set; }
    
        public virtual Comic Comic { get; set; }
        public virtual User User { get; set; }
    }
}
